Сделано ДЗ
crazy30388/homework_OOP pull request #1
Opened 2023-01-13 12:42 UTC by crazy30388

Проверьте ДЗ

2023-01-17 14:54 UTC, volalex commented on src/transport/Car.java
> +        public Key(Boolean remoteStart, Boolean keyLessAccess) {
Тут лучше принимать примитивное значение boolean а не обертку Boolean - так мы обезопасим себя от того что нам могут передать null

2023-01-20 15:43 UTC, crazy30388 commented
Проверьте

2023-01-29 16:32 UTC, OlgaLugacheva requested changes

2023-01-29 16:32 UTC, OlgaLugacheva commented on src/transport/Transport.java
> +    public void printType() {
логично что он будет абстрактным

2023-01-29 16:32 UTC, OlgaLugacheva commented on src/transport/Truck.java
> +
нужна какая-то реализация

2023-01-29 16:32 UTC, OlgaLugacheva commented on src/transport/Bus.java
> +
реализация нужна

2023-01-29 16:33 UTC, OlgaLugacheva requested changes

2023-01-29 16:33 UTC, OlgaLugacheva commented on src/transport/Bus.java
> +        throw new RuntimeException("Автобусы диагностику проходить не должны");
давай свое исключение напишем

2023-02-02 17:38 UTC, OlgaLugacheva requested changes

2023-02-02 17:38 UTC, OlgaLugacheva commented on src/transport/MaintenanceStation.java
> +    Queue<Transport> queue;
модификатор доступа забыт

2023-02-02 17:38 UTC, OlgaLugacheva commented on src/transport/MaintenanceStation.java
> +    public void check_up(){
никаких нижних подчеркиваний в имени метода

2023-02-07 16:04 UTC, merged